"""empty message

Revision ID: 114db85be7a8
Revises: 
Create Date: 2020-10-01 07:54:53.384615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114db85be7a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pitches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owners', sa.String(), nullable=True),
    sa.Column('cohort', sa.String(), nullable=True),
    sa.Column('technologies', sa.String(), nullable=True),
    sa.Column('pitched_p', sa.DateTime(), nullable=True),
    sa.Column('user_p', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_p'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('pitched_c', sa.DateTime(), nullable=True),
    sa.Column('pitch_id', sa.Integer(), nullable=False),
    sa.Column('user_c', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_c'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('star', sa.Integer(), nullable=True),
    sa.Column('pitch_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    op.drop_table('Likes')
    op.drop_table('Dislikes')
    op.drop_table('Pitches')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pitches',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Pitches_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('pitch', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('User_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['User_id'], ['user.id'], name='Pitches_User_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Pitches_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Dislikes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Dislikes_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('User_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Pitch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Pitch_id'], ['Pitches.id'], name='Dislikes_Pitch_id_fkey'),
    sa.ForeignKeyConstraint(['User_id'], ['user.id'], name='Dislikes_User_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Dislikes_pkey')
    )
    op.create_table('Likes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Likes_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('User_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Pitch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Pitch_id'], ['Pitches.id'], name='Likes_Pitch_id_fkey'),
    sa.ForeignKeyConstraint(['User_id'], ['user.id'], name='Likes_User_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Likes_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=55), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=90), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    op.drop_table('stars')
    op.drop_table('comments')
    op.drop_table('pitches')
    op.drop_table('users')
    # ### end Alembic commands ###
